name: Deploy TGBot

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build and run Docker container on remote server
      run: |
          cd ~/weather_bot
          docker stop weather_bot || true
          docker rm weather_bot || true
          docker build -t weather_bot .
          docker run -d --name weather_bot \
            --env TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
            --env WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} \
            weather_bot

    - name: Finish Job
      run: echo "Деплойчик-то прошел))))"